import fs from 'fs';

const keywords = [
  "are temp email safe",
  "is temp email legit",
  "is temporary email",
  "temporary email address",
  "how does temp email work",
  "is it safe to use temp mail",
  "are temporary emails safe",
  "are temporary emails legal",
  "can temp email be tracked",
  "can i use temporary email for instagram",
  "can i use temporary email for chatgpt",
  "can temporary email be traced",
  "can i access a temp email",
  "can i recover a temp email",
  "can i create a temporary email account",
  "can i get a temporary email address",
  "can i make a temporary email",
  "can i create a temporary email account in gmail",
  "can i use a temporary email for discord",
  "does temp email work",
  "do temp emails get deleted",
  "do temp email have password",
  "can you use temp email for twitter",
  "can you recover a temp email",
  "can you use a temp email for discord",
  "can you use a temp email for reddit",
  "how to get temp email",
  "can temp mail be tracked",
  "can temp files be deleted",
  "how do temporary email generator work",
  "how do temporary email addresses work",
  "how to temp email",
  "how do disposable emails work",
  "how long do temp email last",
  "how to create temp email",
  "how to use temp email",
  "how to recover temp email",
  "how to get temp email back",
  "how to access temp email",
  "how to access temp email again",
  "how to check temp email",
  "how to generate temp email",
  "send email from temp",
  "should temporary files be deleted",
  "should tempeh be cooked",
  "should i delete temp files in windows 10",
  "should you put temp jobs on resume",
  "how temp email works",
  "what temp emails work for discord",
  "how create temporary email",
  "how to create temp email id",
  "how to send temp email",
  "how to login temp email",
  "how to create temp email address",
  "how to get temp email address",
  "what's disposable email address",
  "what is temp email",
  "what is temporary email",
  "what is temporary email address",
  "how do i find my temp mail",
  "does temp mail work",
  "what temp emergency room",
  "what temp er",
  "what temp for emergency heat",
  "where are email templates stored",
  "where are email templates saved",
  "where are email templates in salesforce",
  "where are email templates stored in outlook",
  "temp email where you can send",
  "how do i access my temp mail",
  "send temp email",
  "where is email template used salesforce",
  "temp.email address",
  "which temp email is best",
  "what is a temp email",
  "temp email with name",
  "which temp is a fever",
  "which temp is most accurate",
  "which temp files are safe to delete",
  "which temp is more accurate",
  "which temp mail is the best",
  "temp email creator",
  "temp company email",
  "who to email",
  "who is the email",
  "best temp mail for usa",
  "uk disposable email address",
  "australian temp email",
  "canadian temp mail service",
  "temp mail for netflix",
  "temp mail for amazon",
  "temp mail for ebay",
  "temp mail for paypal",
  "temp mail for spotify",
  "temp mail for netflix account",
  "temp mail for amazon account",
  "temp mail for ebay account",
  "temp mail for paypal account",
  "temp mail for spotify account",
  "temp mail for netflix free trial",
  "temp mail for amazon free trial",
  "temp mail for ebay free trial",
  "temp mail for paypal free trial",
  "temp mail for spotify free trial",
  "temp mail for netflix registration",
  "temp mail for amazon registration",
  "temp mail for ebay registration",
  "temp mail for paypal registration",
  "temp mail for spotify registration",
  "temp mail for netflix sign up",
  "temp mail for amazon sign up",
  "temp mail for ebay sign up",
  "temp mail for paypal sign up",
  "temp mail for spotify sign up",
  "temp mail for netflix login",
  "temp mail for amazon login",
  "temp mail for ebay login",
  "temp mail for paypal login",
  "temp mail for spotify login",
  "temp mail for netflix verification",
  "temp mail for amazon verification",
  "temp mail for ebay verification",
  "temp mail for paypal verification",
  "temp mail for spotify verification",
  "temp mail for netflix code",
  "temp mail for amazon code",
  "temp mail for ebay code",
  "temp mail for paypal code",
  "temp mail for spotify code",
  "temp mail for netflix otp",
  "temp mail for amazon otp",
  "temp mail for ebay otp",
  "temp mail for paypal otp",
  "temp mail for spotify otp",
  "temp mail for netflix email",
  "temp mail for amazon email",
  "temp mail for ebay email",
  "temp mail for paypal email",
  "temp mail for spotify email",
  "temp mail for netflix address",
  "temp mail for amazon address",
  "temp mail for ebay address",
  "temp mail for paypal address",
  "temp mail for spotify address",
  "temp mail for netflix account creation",
  "temp mail for amazon account creation",
  "temp mail for ebay account creation",
  "temp mail for paypal account creation",
  "temp mail for spotify account creation",
  "temp mail for netflix account verification",
  "temp mail for amazon account verification",
  "temp mail for ebay account verification",
  "temp mail for paypal account verification",
  "temp mail for spotify account verification",
  "temp mail for netflix account code",
  "temp mail for amazon account code",
  "temp mail for ebay account code",
  "temp mail for paypal account code",
  "temp mail for spotify account code",
  "temp mail for netflix account otp",
  "temp mail for amazon account otp",
  "temp mail for ebay account otp",
  "temp mail for paypal account otp",
  "temp mail for spotify account otp",
  "temp mail for netflix account email",
  "temp mail for amazon account email",
  "temp mail for ebay account email",
  "temp mail for paypal account email",
  "temp mail for spotify account email",
  "temp mail for netflix account address",
  "temp mail for amazon account address",
  "temp mail for ebay account address",
  "temp mail for paypal account address",
  "temp mail for spotify account address",
  "temp mail for netflix account sign up",
  "temp mail for amazon account sign up",
  "temp mail for ebay account sign up",
  "temp mail for paypal account sign up",
  "temp mail for spotify account sign up",
  "temp mail for netflix account login",
  "temp mail for amazon account login",
  "temp mail for ebay account login",
  "temp mail for paypal account login",
  "temp mail for spotify account login",
  "temp mail for netflix account verification code",
  "temp mail for amazon account verification code",
  "temp mail for ebay account verification code",
  "temp mail for paypal account verification code",
  "temp mail for spotify account verification code",
  "temp mail for netflix account verification otp",
  "temp mail for amazon account verification otp",
  "temp mail for ebay account verification otp",
  "temp mail for paypal account verification otp",
  "temp mail for spotify account verification otp",
  "temp mail for netflix account verification email",
  "temp mail for amazon account verification email",
  "temp mail for ebay account verification email",
  "temp mail for paypal account verification email",
  "temp mail for spotify account verification email",
  "temp mail for netflix account verification address",
  "temp mail for amazon account verification address",
  "temp mail for ebay account verification address",
  "temp mail for paypal account verification address",
  "temp mail for spotify account verification address",
  "temp mail for netflix account verification sign up",
  "temp mail for amazon account verification sign up",
  "temp mail for ebay account verification sign up",
  "temp mail for paypal account verification sign up",
  "temp mail for spotify account verification sign up",
  "temp mail for netflix account verification login",
  "temp mail for amazon account verification login",
  "temp mail for ebay account verification login",
  "temp mail for paypal account verification login",
  "temp mail for spotify account verification login",
  "temp mail for netflix account verification code email",
  "temp mail for amazon account verification code email",
  "temp mail for ebay account verification code email",
  "temp mail for paypal account verification code email",
  "temp mail for spotify account verification code email",
  "temp mail for netflix account verification code address",
  "temp mail for amazon account verification code address",
  "temp mail for ebay account verification code address",
  "temp mail for paypal account verification code address",
  "temp mail for spotify account verification code address",
  "temp mail for netflix account verification code sign up",
  "temp mail for amazon account verification code sign up",
  "temp mail for ebay account verification code sign up",
  "temp mail for paypal account verification code sign up",
  "temp mail for spotify account verification code sign up",
  "temp mail for netflix account verification code login",
  "temp mail for amazon account verification code login",
  "temp mail for ebay account verification code login",
  "temp mail for paypal account verification code login",
  "temp mail for spotify account verification code login",
  "temp mail for netflix account verification code verification",
  "temp mail for amazon account verification code verification",
  "temp mail for ebay account verification code verification",
  "temp mail for paypal account verification code verification",
  "temp mail for spotify account verification code verification",
  "temp mail for netflix account verification code otp",
  "temp mail for amazon account verification code otp",
  "temp mail for ebay account verification code otp",
  "temp mail for paypal account verification code otp",
  "temp mail for spotify account verification code otp",
  "temp mail for netflix account verification code email address",
  "temp mail for amazon account verification code email address",
  "temp mail for ebay account verification code email address",
  "temp mail for paypal account verification code email address",
  "temp mail for spotify account verification code email address",
  "temp mail for netflix account verification code sign up account",
  "temp mail for amazon account verification code sign up account",
  "temp mail for ebay account verification code sign up account",
  "temp mail for paypal account verification code sign up account",
  "temp mail for spotify account verification code sign up account",
  "temp mail for netflix account verification code login account",
  "temp mail for amazon account verification code login account",
  "temp mail for ebay account verification code login account",
  "temp mail for paypal account verification code login account",
  "temp mail for spotify account verification code login account",
  "temp mail for netflix account verification code verification code",
  "temp mail for amazon account verification code verification code",
  "temp mail for ebay account verification code verification code",
  "temp mail for paypal account verification code verification code",
  "temp mail for spotify account verification code verification code",
  "temp mail for netflix account verification code otp code",
  "temp mail for amazon account verification code otp code",
  "temp mail for ebay account verification code otp code",
  "temp mail for paypal account verification code otp code",
  "temp mail for spotify account verification code otp code",
  "temp mail for netflix account verification code email address account",
  "temp mail for amazon account verification code email address account",
  "temp mail for ebay account verification code email address account",
  "temp mail for paypal account verification code email address account",
  "temp mail for spotify account verification code email address account",
];


let content = fs.readFileSync('data/seoPages.ts', 'utf8');

// Remove the closing bracket and semicolon
content = content.replace(/\];\s*$/, '');

keywords.forEach(kw => {
    const slug = kw.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
    if (!content.includes(`slug: '${slug}'`)) {
        const title = kw.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
        content += `    {
        slug: '${slug}',
        title: '${title} - Temp Mail Guide',
        description: 'Learn everything about ${kw}. Read our comprehensive guide on disposable email services.',
        keywords: ['${kw}', 'temp mail', 'disposable email', 'anonymous email'],
        h1: '${title}',
        content: 'Find out the answer to ${kw}. Our temporary email service provides secure, anonymous, and fast disposable email addresses to help you protect your privacy online.'
    },\n`;
    }
});

content += "];\n";

fs.writeFileSync('data/seoPages.ts', content);
