const countries = [
  { slug: 'uk', name: 'UK', code: 'GB', lang: 'en', term: 'Temp mail' },
  { slug: 'germany', name: 'Germany', code: 'DE', lang: 'de', term: 'Einweg e-mail' },
  { slug: 'france', name: 'France', code: 'FR', lang: 'fr', term: 'Email jetable' },
  { slug: 'italy', name: 'Italy', code: 'IT', lang: 'it', term: 'Email temporanea' },
  { slug: 'spain', name: 'Spain', code: 'ES', lang: 'es', term: 'Correo temporal' },
  { slug: 'netherlands', name: 'Netherlands', code: 'NL', lang: 'nl', term: 'Tijdelijke e-mail' },
  { slug: 'switzerland', name: 'Switzerland', code: 'CH', lang: 'de', term: 'Einweg e-mail' },
  { slug: 'sweden', name: 'Sweden', code: 'SE', lang: 'sv', term: 'Tillfällig e-post' },
  { slug: 'norway', name: 'Norway', code: 'NO', lang: 'no', term: 'Midlertidig e-post' },
  { slug: 'denmark', name: 'Denmark', code: 'DK', lang: 'da', term: 'Midlertidig e-mail' },
  { slug: 'finland', name: 'Finland', code: 'FI', lang: 'fi', term: 'Väliaikainen sähköposti' },
  { slug: 'ireland', name: 'Ireland', code: 'IE', lang: 'en', term: 'Temp mail' },
  { slug: 'belgium', name: 'Belgium', code: 'BE', lang: 'nl', term: 'Tijdelijke e-mail' },
  { slug: 'austria', name: 'Austria', code: 'AT', lang: 'de', term: 'Einweg e-mail' },
  { slug: 'portugal', name: 'Portugal', code: 'PT', lang: 'pt', term: 'Email temporário' },
  { slug: 'greece', name: 'Greece', code: 'GR', lang: 'el', term: 'Prosorinó email' },
  { slug: 'poland', name: 'Poland', code: 'PL', lang: 'pl', term: 'Tymczasowy e-mail' },
  { slug: 'czech-republic', name: 'Czech Republic', code: 'CZ', lang: 'cs', term: 'Dočasný e-mail' },
  { slug: 'luxembourg', name: 'Luxembourg', code: 'LU', lang: 'fr', term: 'Email jetable' },
  { slug: 'monaco', name: 'Monaco', code: 'MC', lang: 'fr', term: 'Email jetable' },
  { slug: 'iceland', name: 'Iceland', code: 'IS', lang: 'is', term: 'Tímabundið netfang' },
  { slug: 'hungary', name: 'Hungary', code: 'HU', lang: 'hu', term: 'Ideiglenes e-mail' },
  { slug: 'slovakia', name: 'Slovakia', code: 'SK', lang: 'sk', term: 'Dočasný e-mail' },
  { slug: 'romania', name: 'Romania', code: 'RO', lang: 'ro', term: 'Email temporar' },
  { slug: 'bulgaria', name: 'Bulgaria', code: 'BG', lang: 'bg', term: 'Vremenno imeyl' },
  { slug: 'croatia', name: 'Croatia', code: 'HR', lang: 'hr', term: 'Privremeni e-mail' },
  { slug: 'slovenia', name: 'Slovenia', code: 'SI', lang: 'sl', term: 'Začasni e-mail' },
  { slug: 'estonia', name: 'Estonia', code: 'EE', lang: 'et', term: 'Ajutine e-post' },
  { slug: 'latvia', name: 'Latvia', code: 'LV', lang: 'lv', term: 'Pagaidu e-pasts' },
  { slug: 'lithuania', name: 'Lithuania', code: 'LT', lang: 'lt', term: 'Laikinas el. paštas' },
  { slug: 'bosnia', name: 'Bosnia', code: 'BA', lang: 'bs', term: 'Privremeni e-mail' },
  { slug: 'russia', name: 'Russia', code: 'RU', lang: 'ru', term: 'Vremennaya pochta' },
  { slug: 'turkey', name: 'Turkey', code: 'TR', lang: 'tr', term: 'Geçici e-posta' },
  { slug: 'usa', name: 'USA', code: 'US', lang: 'en', term: 'Temp mail' },
  { slug: 'canada', name: 'Canada', code: 'CA', lang: 'en', term: 'Temp mail' },
  { slug: 'mexico', name: 'Mexico', code: 'MX', lang: 'es', term: 'Correo temporal' },
  { slug: 'brazil', name: 'Brazil', code: 'BR', lang: 'pt', term: 'Email temporário' },
  { slug: 'argentina', name: 'Argentina', code: 'AR', lang: 'es', term: 'Correo temporal' },
  { slug: 'chile', name: 'Chile', code: 'CL', lang: 'es', term: 'Correo temporal' },
  { slug: 'colombia', name: 'Colombia', code: 'CO', lang: 'es', term: 'Correo temporal' },
  { slug: 'peru', name: 'Peru', code: 'PE', lang: 'es', term: 'Correo temporal' },
  { slug: 'uruguay', name: 'Uruguay', code: 'UY', lang: 'es', term: 'Correo temporal' },
  { slug: 'ecuador', name: 'Ecuador', code: 'EC', lang: 'es', term: 'Correo temporal' },
  { slug: 'costa-rica', name: 'Costa Rica', code: 'CR', lang: 'es', term: 'Correo temporal' },
  { slug: 'panama', name: 'Panama', code: 'PA', lang: 'es', term: 'Correo temporal' },
  { slug: 'japan', name: 'Japan', code: 'JP', lang: 'ja', term: 'Sute meado' },
  { slug: 'south-korea', name: 'South Korea', code: 'KR', lang: 'ko', term: 'Ilhoeyong imeil' },
  { slug: 'china', name: 'China', code: 'CN', lang: 'zh', term: 'Linshi youxiang' },
  { slug: 'taiwan', name: 'Taiwan', code: 'TW', lang: 'zh', term: 'Linshi youxiang' },
  { slug: 'hong-kong', name: 'Hong Kong', code: 'HK', lang: 'zh', term: 'Linshi youxiang' },
  { slug: 'singapore', name: 'Singapore', code: 'SG', lang: 'en', term: 'Temp mail' },
  { slug: 'australia', name: 'Australia', code: 'AU', lang: 'en', term: 'Temp mail' },
  { slug: 'new-zealand', name: 'New Zealand', code: 'NZ', lang: 'en', term: 'Temp mail' },
  { slug: 'uae', name: 'UAE', code: 'AE', lang: 'ar', term: 'Barid muwaqqat' },
  { slug: 'saudi-arabia', name: 'Saudi Arabia', code: 'SA', lang: 'ar', term: 'Barid muwaqqat' },
  { slug: 'qatar', name: 'Qatar', code: 'QA', lang: 'ar', term: 'Barid muwaqqat' },
  { slug: 'kuwait', name: 'Kuwait', code: 'KW', lang: 'ar', term: 'Barid muwaqqat' },
  { slug: 'oman', name: 'Oman', code: 'OM', lang: 'ar', term: 'Barid muwaqqat' },
  { slug: 'malaysia', name: 'Malaysia', code: 'MY', lang: 'ms', term: 'E-mel sementara' },
  { slug: 'thailand', name: 'Thailand', code: 'TH', lang: 'th', term: 'Ximel chawkraw' },
  { slug: 'indonesia', name: 'Indonesia', code: 'ID', lang: 'id', term: 'Email sementara' },
  { slug: 'philippines', name: 'Philippines', code: 'PH', lang: 'en', term: 'Temp mail' },
  { slug: 'south-africa', name: 'South Africa', code: 'ZA', lang: 'en', term: 'Temp mail' },
  { slug: 'nigeria', name: 'Nigeria', code: 'NG', lang: 'en', term: 'Temp mail' },
  { slug: 'egypt', name: 'Egypt', code: 'EG', lang: 'ar', term: 'Barid muwaqqat' },
  { slug: 'kenya', name: 'Kenya', code: 'KE', lang: 'en', term: 'Temp mail' },
  { slug: 'morocco', name: 'Morocco', code: 'MA', lang: 'ar', term: 'Barid muwaqqat' },
  { slug: 'namibia', name: 'Namibia', code: 'NA', lang: 'en', term: 'Temp mail' },
  { slug: 'algeria', name: 'Algeria', code: 'DZ', lang: 'ar', term: 'Barid muwaqqat' },
  { slug: 'tunisia', name: 'Tunisia', code: 'TN', lang: 'ar', term: 'Barid muwaqqat' }
];

const useCases = [
    { suffix: '', titleSuffix: '' },
    { suffix: '-for-facebook', titleSuffix: 'for Facebook' },
    { suffix: '-for-instagram', titleSuffix: 'for Instagram' },
    { suffix: '-for-discord', titleSuffix: 'for Discord' },
    { suffix: '-for-verification', titleSuffix: 'for Verification' },
    { suffix: '-for-gaming', titleSuffix: 'for Gaming' },
    { suffix: '-for-business', titleSuffix: 'for Business' },
    { suffix: '-for-dating', titleSuffix: 'for Dating' },
    { suffix: '-for-students', titleSuffix: 'for Students' },
    { suffix: '-for-steam', titleSuffix: 'for Steam' },
    { suffix: '-for-fortnite', titleSuffix: 'for Fortnite' },
    { suffix: '-for-gmail', titleSuffix: 'for Gmail' },
    { suffix: '-for-tiktok', titleSuffix: 'for TikTok' },
    { suffix: '-for-twitter', titleSuffix: 'for Twitter' },
    { suffix: '-for-reddit', titleSuffix: 'for Reddit' },
    { suffix: '-for-spotify', titleSuffix: 'for Spotify' },
    { suffix: '-for-netflix', titleSuffix: 'for Netflix' },
    { suffix: '-for-amazon', titleSuffix: 'for Amazon' },
    { suffix: '-for-ebay', titleSuffix: 'for eBay' },
    { suffix: '-for-paypal', titleSuffix: 'for PayPal' },
    { suffix: '-for-crypto', titleSuffix: 'for Crypto' },
    { suffix: '-for-trading', titleSuffix: 'for Trading' },
    { suffix: '-for-education', titleSuffix: 'for Education' },
    { suffix: '-for-jobs', titleSuffix: 'for Jobs' }
];

module.exports = { countries, useCases };
